MNT: Re-rendered with conda-build 3.19.2 and conda-smithy 3.7.1
nsls-ii-forge/xpdan-feedstock pull request #1
Opened 2020-05-13 18:37 UTC by tienhungvuong

2020-05-18 17:29 UTC, tienhungvuong commented
Hi @tacaswell! Could you review this PR before it can be merged?

2020-05-18 18:26 UTC, mrakitin requested changes
I think the URL in `meta.yaml` (`git_url: https://github.com/xpdAcq/xpdAn.git`) should be changed to the tagged .tar.gz file from https://github.com/xpdAcq/xpdAn/releases/tag/0.8.1.

Also, could you please add a summary entry in the `about:` section?

2020-05-18 19:03 UTC, tienhungvuong commented
Hi @mrakitin! Thank you for your feedback. I changed the git_url and added the summary but the tests failed. Could you check if the url I added was correct?

2020-05-18 19:51 UTC, mrakitin reviewed
Thanks @tienhungvuong! I put a couple of suggestions to solve the issue.

We also parametrize the name of the package and provide its `sha256` hash. Do you mind to also update it? https://github.com/nsls-ii-forge/bluesky-feedstock/blob/master/recipe/meta.yaml is a good example how it should look. Thanks!

2020-05-18 19:51 UTC, mrakitin commented on recipe/meta.yaml
> +  git_url: https://github.com/xpdAcq/xpdAn/releases/download/0.8.1/xpdAn-0.8.1.tar.gz
```suggestion
  url: https://github.com/xpdAcq/xpdAn/releases/download/{{ version }}/xpdAn-{{ version }}.tar.gz
```

2020-05-18 19:51 UTC, mrakitin commented on recipe/meta.yaml
>    git_rev: {{ version }}
```suggestion
```

2020-05-18 19:51 UTC, mrakitin commented on recipe/meta.yaml
>    git_depth: -1
```suggestion
```

2020-05-18 19:51 UTC, mrakitin commented on recipe/meta.yaml
> +  summary: Python package that aids data analysis at the XPD Beamline.
```suggestion
  summary: Python package that aids data analysis at the NSLS-II XPD Beamline.
```

2020-05-19 20:48 UTC, tienhungvuong commented
Thank you very much @mrakitin! Where can I find the sha256 hash of the package?

2020-05-19 22:52 UTC, mrakitin commented
Here are some recommendations: https://github.com/conda-forge/staged-recipes/wiki/Frequently-asked-questions#2-how-do-i-populate-the-hash-field.

I normally download the archive which is going to be used by the conda-build, and run this:
```bash
$ openssl sha256 <file name>
```

2020-05-19 22:55 UTC, mrakitin commented
More formal instructions are here: https://conda-forge.org/docs/maintainer/adding_pkgs.html#populating-the-hash-field.

I prefer to download the file first to make sure it's a proper archive.

2020-05-20 18:51 UTC, tienhungvuong commented
Hi @mrakitin! I made the changes you suggested. Could you review this PR to see if it can be merged?

2020-05-20 22:44 UTC, mrakitin requested changes
Please fix one more issue indicated below.
@tacaswell, do you mind to re-review the updates in `meta.yaml` and merge (I'll try to keep away from my computer for some time)? Thanks!

2020-05-20 22:44 UTC, mrakitin commented on recipe/meta.yaml
> +  sha256: {{ sha256 }}
This should go to the `source` group. The rest looks OK.

2020-06-01 22:58 UTC, mrakitin approved these changes
Thanks, @tienhungvuong!

2020-06-01 22:59 UTC, merged

2020-06-19 01:19 UTC, mrakitin commented
@tienhungvuong, this package is missing the `xpdtools` dependency in this `nsls2forge` channel, so it took the missing dep from `conda-forge` instead. That's the behavior we want to avoid. Could you please build the missing dependency. Also, for one of the dependencies, there was a hard pin of databroker 0.13. That should be relaxed as we are going to deploy databroker 1.0 soon.

2020-06-30 17:43 UTC, tienhungvuong commented
@mrakitin Sorry for the late reply because I didn't get the notifications for some reasons. I'm working on building xpdtools now. Could you create a repo for `xpdtools-feedstocks` so I can push to? Thank you very much!

2020-06-30 19:03 UTC, mrakitin commented
Done via https://github.com/nsls-ii-forge/xpdtools-feedstock/pull/1. Once merged, please go ahead and update to reflect the latest/proper dependencies.